# https://travis-ci.org/segfault/python-bdateutil

language: python

python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
    - 3.7
    - pypy
    - pypy3.5

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
    - python setup.py install
    - pip install coveralls flake8 pytest pytest-cov codecov

before_script:
    - flake8 bdateutil/*.py tests.py --ignore=F401,E402,F403,F405,W504

script:
    - coverage run --omit=*site-packages*,*pypy*,*dateutil_tests/* tests.py

after_success:
    - coveralls
